//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace guestHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomBook
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string checkIn { get; set; }
        public string checkOut { get; set; }
        public Nullable<int> numberOfPeople { get; set; }
        public string comments { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
